language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:

    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="4cf10a0d-086d-4435-8002-3c8177df737e"